declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'
declare module 'msr'
declare module 'react-facebook-login'
declare module 'react-responsive-modal'
declare module '@material-ui/core'

declare module 'styled-components'
declare module 'react-simple-chatbot'